# Generated by Django 5.1.7 on 2026-08-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharedSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source_path", models.CharField(max_length=500)),
                ("last_synced_commit", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SharedSkillRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("git_commit", models.CharField(max_length=64)),
                ("archive_name", models.CharField(max_length=255)),
                ("archive_remote_path", models.CharField(max_length=1000)),
                ("archive_size", models.BigIntegerField()),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="skills.sharedskill",
                    ),
                ),
            ],
            options={
                "ordering": ("-synced_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("skill", "git_commit"),
                        name="unique_skill_release_commit",
                    )
                ],
            },
        ),
    ]
