# Generated by Django 5.1.7 on 2026-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sharedskillrelease",
            name="unique_skill_release_commit",
        ),
        migrations.AddField(
            model_name="sharedskillrelease",
            name="repository_id",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddConstraint(
            model_name="sharedskillrelease",
            constraint=models.UniqueConstraint(
                fields=("skill", "git_commit", "repository_id"),
                name="unique_skill_release_commit_repository",
            ),
        ),
    ]
