# Generated by Django 5.2.17 on 2026-08-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0011_skillsyncjob_heartbeat_and_active_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSkillRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, unique=True)),
                ("skill_path", models.CharField(max_length=500)),
                ("recommendation", models.TextField()),
                ("stars", models.PositiveIntegerField(default=0)),
                ("repository_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("blob_sha", models.CharField(max_length=64)),
                ("ai_model", models.CharField(max_length=120)),
                ("ai_prompt_version", models.CharField(max_length=80)),
                ("refreshed_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-stars", "-repository_pushed_at", "full_name"),
            },
        ),
        migrations.AlterField(
            model_name="skillsyncjob",
            name="operation",
            field=models.CharField(
                choices=[
                    ("sync", "GitHub sync"),
                    ("scan", "GitHub candidate scan"),
                    ("enrichment", "Summary and classification"),
                    ("recommendation", "Academic Skill recommendations"),
                ],
                default="scan",
                max_length=20,
            ),
        ),
    ]
