# Generated by Django 5.2.17 on 2026-09-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0014_skillinstall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedskillrelease",
            name="storage_backend",
            field=models.CharField(
                choices=[("nas_webdav", "NAS WebDAV"), ("local", "Local filesystem")],
                default="nas_webdav",
                max_length=20,
            ),
        ),
    ]
