# Generated by Django 5.2.17 on 2026-08-31 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("box_upload", "0009_upload_review_staging"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("download", "Download PDF"),
                            ("parse", "Parse PDF"),
                            ("chunk", "Create chunks"),
                            ("overview", "Generate overview"),
                            ("complete", "Complete"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("pipeline_version", models.CharField(max_length=64)),
                ("parser_version", models.CharField(max_length=64)),
                ("chunker_version", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=64)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="box_upload.uploadeddocument",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="DocumentParse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parser_name", models.CharField(max_length=64)),
                ("parser_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=64)),
                ("page_count", models.PositiveIntegerField()),
                ("artifact_storage_backend", models.CharField(max_length=32)),
                ("artifact_path", models.CharField(max_length=1000)),
                ("artifact_sha256", models.CharField(max_length=64)),
                (
                    "artifact_content_type",
                    models.CharField(default="application/json", max_length=255),
                ),
                ("artifact_size", models.PositiveBigIntegerField()),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_parse",
                        to="literature_processing.documentprocessingjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="LiteratureChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_key", models.CharField(max_length=128)),
                ("sequence", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField()),
                ("page_sequence", models.PositiveIntegerField()),
                ("start_offset", models.PositiveIntegerField()),
                ("end_offset", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_parse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="literature_processing.documentparse",
                    ),
                ),
            ],
            options={
                "ordering": ("document_parse_id", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(choices=[("overview", "Overview")], max_length=32),
                ),
                ("schema_version", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=64)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_parse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="literature_processing.documentparse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "document_parse",
                            "analysis_type",
                            "prompt_version",
                            "input_fingerprint",
                        ),
                        name="lp_unique_analysis_input",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="documentprocessingjob",
            index=models.Index(
                fields=["status", "created_at"], name="lp_job_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentprocessingjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("queued", "running"))),
                fields=("uploaded_document",),
                name="lp_unique_active_job",
            ),
        ),
        migrations.AddIndex(
            model_name="literaturechunk",
            index=models.Index(
                fields=["document_parse", "page_number"], name="lp_chunk_page_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturechunk",
            constraint=models.UniqueConstraint(
                fields=("document_parse", "chunk_key"), name="lp_unique_chunk_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturechunk",
            constraint=models.UniqueConstraint(
                fields=("document_parse", "sequence"), name="lp_unique_chunk_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturechunk",
            constraint=models.UniqueConstraint(
                fields=("document_parse", "page_number", "page_sequence"),
                name="lp_unique_page_chunk",
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturechunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_number__gte", 1)),
                name="lp_chunk_page_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturechunk",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset__gt", models.F("start_offset"))),
                name="lp_chunk_offsets_valid",
            ),
        ),
    ]
