# Generated by Django 5.2.17 on 2026-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentparse",
            name="raw_artifact_content_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="documentparse",
            name="raw_artifact_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="documentparse",
            name="raw_artifact_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="documentparse",
            name="raw_artifact_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentparse",
            name="raw_artifact_storage_backend",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="documentparse",
            name="runtime_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="parser_name",
            field=models.CharField(default="pypdf", max_length=64),
        ),
        migrations.AddField(
            model_name="literaturechunk",
            name="end_page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="literaturechunk",
            name="section_path",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="literaturechunk",
            name="source_spans",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="literaturechunk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_page_number__isnull", True),
                    ("end_page_number__gte", models.F("page_number")),
                    _connector="OR",
                ),
                name="lp_chunk_page_range_valid",
            ),
        ),
    ]
