# Generated by Django 5.2.17 on 2026-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_upload", "0009_upload_review_staging"),
        (
            "literature_processing",
            "0002_documentparse_raw_artifact_content_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentprocessingjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="progress_current",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="progress_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="progress_unit",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="provider_batch_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="provider_state",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="queue_lane",
            field=models.CharField(
                choices=[("realtime", "Realtime"), ("backfill", "Backfill")],
                db_index=True,
                default="backfill",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="documentprocessingjob",
            name="worker_channel",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="documentprocessingjob",
            index=models.Index(
                fields=["queue_lane", "status", "created_at"],
                name="lp_job_lane_queue_idx",
            ),
        ),
    ]
