# Generated by Django 5.2.17 on 2026-09-28 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature_processing", "0003_documentprocessingjob_heartbeat_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentanalysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("overview", "Overview"),
                    ("paper_skeleton", "Paper skeleton"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PaperConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_parse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_conversations",
                        to="literature_processing.documentparse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PaperChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_uuid", models.UUIDField(default=uuid.uuid4)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("structured_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="succeeded",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("requested_model", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=64)),
                ("schema_version", models.CharField(blank=True, max_length=64)),
                ("input_fingerprint", models.CharField(blank=True, max_length=64)),
                ("context_manifest", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="literature_processing.paperconversation",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "sequence"),
                        name="lp_chat_sequence_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("request_id", ""), _negated=True),
                        fields=("conversation", "request_id"),
                        name="lp_chat_request_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("role", "assistant"), ("status", "pending")
                        ),
                        fields=("conversation",),
                        name="lp_chat_pending_unique",
                    ),
                ],
            },
        ),
    ]
