# Generated by Django 5.2.17 on 2026-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature_processing", "0004_alter_documentanalysis_analysis_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paperchatmessage",
            name="lp_chat_request_unique",
        ),
        migrations.AddConstraint(
            model_name="paperchatmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("role", "assistant"), models.Q(("request_id", ""), _negated=True)
                ),
                fields=("conversation", "request_id"),
                name="lp_chat_request_unique",
            ),
        ),
    ]
