# Generated by Django 5.2.17 on 2026-09-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "literature_processing",
            "0005_remove_paperchatmessage_lp_chat_request_unique_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=128)),
                (
                    "analysis_type",
                    models.CharField(default="paper_skeleton", max_length=32),
                ),
                ("generation_key", models.CharField(max_length=64)),
                ("generation_nonce", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("requested_model", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=64)),
                ("schema_version", models.CharField(blank=True, max_length=64)),
                ("context_manifest", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_parse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_analysis_runs",
                        to="literature_processing.documentparse",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_analysis_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skeleton_runs",
                        to="literature_processing.documentanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("request_id", ""), _negated=True),
                        fields=("requested_by", "request_id"),
                        name="lp_skeleton_request_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("pending", "running"))),
                        fields=("document_parse", "analysis_type"),
                        name="lp_skeleton_pending_unique",
                    ),
                ],
            },
        ),
    ]
