# Generated by Django 5.1.7 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canonicaldocument",
            name="sha256",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="abstract",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="ai_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="authors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="identifiers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="journal",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="metadata_candidates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="metadata_confidence",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="metadata_evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="metadata_source",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="metadata_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("incomplete", "Incomplete"),
                    ("needs_review", "Needs review"),
                    ("verified", "Verified"),
                    ("conflict", "Conflict"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="source_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="canonicaldocument",
            name="user_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="canonicaldocument",
            name="index_status",
            field=models.CharField(
                choices=[("pending", "Pending review"), ("published", "Published")],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("zotero", "Zotero")], max_length=32),
                ),
                ("library_id", models.CharField(max_length=255)),
                ("external_item_id", models.CharField(max_length=255)),
                ("external_version", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="box_upload.canonicaldocument",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalreference",
            constraint=models.UniqueConstraint(
                fields=("provider", "library_id", "external_item_id"),
                name="unique_external_literature_reference",
            ),
        ),
    ]
