# Generated by Django 5.1.7 on 2026-08-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_upload", "0002_literature_metadata_and_external_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("stale", "Stale")], default="queued", max_length=16)),
                ("provider", models.CharField(default="deepseek", max_length=32)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=64)),
                ("input_fingerprint", models.CharField(blank=True, max_length=64)),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                ("proposal", models.JSONField(blank=True, default=dict)),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("canonical_updated_at", models.DateTimeField()),
                ("accepted_before", models.JSONField(blank=True, default=dict)),
                ("accepted_after", models.JSONField(blank=True, default=dict)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("canonical_document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metadata_proposals", to="box_upload.canonicaldocument")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_metadata_proposals", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_metadata_proposals", to=settings.AUTH_USER_MODEL)),
                ("source_upload", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="metadata_proposals", to="box_upload.uploadeddocument")),
            ],
            options={"ordering": ("-requested_at",)},
        ),
        migrations.AddConstraint(
            model_name="metadataproposal",
            constraint=models.UniqueConstraint(condition=models.Q(status__in=("queued", "running")), fields=("canonical_document",), name="unique_active_metadata_proposal"),
        ),
    ]
