# Generated by Django 5.2.17 on 2026-09-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_upload", "0009_upload_review_staging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeddocument",
            name="storage_backend",
            field=models.CharField(
                choices=[("local", "Local filesystem"), ("nas_webdav", "NAS WebDAV")],
                db_index=True,
                default="nas_webdav",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="uploadreviewitem",
            name="storage_backend",
            field=models.CharField(
                choices=[("local", "Local filesystem"), ("nas_webdav", "NAS WebDAV")],
                default="nas_webdav",
                max_length=32,
            ),
        ),
    ]
